<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>conf</string>
		<string>conf.example</string>
	</array>
	<key>name</key>
	<string>InspIRCd Configuration</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#malformed</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block</key>
		<dict>
			<key>begin</key>
			<string>&lt;[A-Za-z0-9-_]+</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.inspircd-configuration</string>
				</dict>
			</dict>
			<key>end</key>
			<string>&gt;</string>
			<key>name</key>
			<string>entity.name.type.inspircd-configuration</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#key</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#malformed</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>begin</key>
			<string>#</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.inspircd-configuration</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.number-sign.inspircd-configuration</string>
		</dict>
		<key>key</key>
		<dict>
			<key>begin</key>
			<string>(?:^|\s)([A-Za-z0-9-_]+)\s*=\s*(")</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.inspircd-configuration</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.section.begin.inspircd-configuration</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.section.end.inspircd-configuration</string>
				</dict>
			</dict>
			<key>name</key>
			<string>entity.name.function.inspircd-configuration</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#value</string>
				</dict>
			</array>
		</dict>
		<key>malformed</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.inspircd-configuration</string>
				</dict>
			</dict>
			<key>match</key>
			<string>[^\s\t]</string>
			<key>name</key>
			<string>invalid.illegal.inspircd-configuration</string>
		</dict>
		<key>value</key>
		<dict>
			<key>match</key>
			<string>[^"]</string>
			<key>name</key>
			<string>string.quoted.double</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.inspircd-config</string>
	<key>uuid</key>
	<string>398238EE-6A78-4E13-9FE5-91CED56272C4</string>
</dict>
</plist>
